name: iyteliden_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  google_fonts:
  flutter_dotenv:
  http:
  shared_preferences:
  http_parser:
  mime:
  image_picker:
  file_picker:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
